### ISSUE TITLE
[Question] MySQL pool limit

### ISSUE THREAD

**Issue by WolverStones** [Realizedd/TokenManager#30]
can I set the limit for mysql pool?

config:
```

# DO NOT EDIT THIS VALUE!
config-version: 8

# If enabled, a notification and the download link will be printed on console whenever an update is available.
check-for-updates: true

# Allows you to force set the plugin's mode to online/offline/automatic.
# If you run a cracked server but the plugin detects it as online and saves UUID instead of name, set the value below to 'false'.
# Available modes: true, false, auto (default)
online-mode: auto

# Prevents players from sending token to a player who has the same ip address as the sender.
alt-prevention: false

# The default token balance of a first-time joiner.
default-balance: 0

# Sets a min/max limit on the amount specified in /token send command. To disable, set the value to -1.
send-amount-limit:
  min: 1
  max: -1

shop:
  # When the command '/token shop' is executed, enabling this option will open the specified shop below. (Even if a shop name is provided)
  open-selected:
    enabled: false
    shop: test

  # Settings for the confirm purchase gui.
  confirm-purchase-gui:
    title: Confirm Your Purchase
    # Use the placeholder %price% in the name or the lore of the confirm-button to display the price of the item to be purchased.
    # NOTE: In Minecraft 1.13, stained glass panes were assigned their own material name. If buttons below won't load, use the new material name.
    confirm-button: STAINED_CLAY:5 1 name:&a&lBUY lore:&7Price:_&a%price%_tokens
    cancel-button: STAINED_CLAY:14 1 name:&c&lCANCEL

  # Set a delay between purchases. 0 for no delay.
  click-delay: 0

  # If enabled, players with full inventory will not be able to purchase from token shops.
  check-inventory-full: false

# [WARNING: DANGER ZONE]
data:
  # If enabled, the plugin will use selected MySQL database as the token balance storage.
  # Note: To transfer all data from data.yml to the MySQL database, use the command '/tm transfer'. (MySQL must be enabled below!)
  mysql:
    enabled: true
    hostname: casa37.fakaheda.eu
    port: '3306'
    username: 288818_mysql_db
    password: 
    database: 288818_mysql_db
    table: tokenmanager
    url: jdbc:mysql://%hostname%:%port%/%database%

    # This section is optional. Using mysql database for a single server will work just fine even if no redis server is provided.
    # If mysql is enabled, a redis server can be used to synchronize balances as they are modified.
    redis:
      enabled: false
      server: 127.0.0.1
      port: '6379'
      password: ''

  # WARNING
  #
  # 1. Enabling this will set TokenManager's economy as your server's main economy.
  # Your old economy data will most likely RESET, and commands related to Economy
  # such as Essentials' /eco won't function properly if target player is offline.
  #
  # 2. If you're using Essentials Economy, make sure to reset everyone's balance
  # before enabling this option! Otherwise, the old Essentials balance of the players
  # might act as a token balance.
  #
  register-economy: false

  # /token top will be updated every x minutes. Value must be higher than 0!
  balance-top-update-interval: 5
```

```
[04:29:20] [Server thread/INFO]: [TokenManager] [0;31;1mCause of error: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.[m
[04:29:20] [Server thread/WARN]: me.realized.tokenmanager.shaded.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:569)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:555)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.data.database.MySQLDatabase.setup(MySQLDatabase.java:110)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.data.DataManager.handleLoad(DataManager.java:86)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.TokenManagerPlugin.load(TokenManagerPlugin.java:155)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.TokenManagerPlugin.onEnable(TokenManagerPlugin.java:106)
[04:29:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[04:29:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[04:29:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[04:29:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[04:29:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[04:29:20] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[04:29:20] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[04:29:20] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[04:29:20] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[04:29:20] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[04:29:20] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:29:20] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[04:29:20] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:29:20] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:29:20] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:29:20] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:632)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1016)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[04:29:20] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:29:20] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:29:20] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:29:20] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
[04:29:20] [Server thread/WARN]: 	at me.realized.tokenmanager.shaded.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
[04:29:20] [Server thread/WARN]: 	... 17 more
[04:29:20] [Server thread/WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[04:29:20] [Server thread/WARN]: 	at java.net.SocketInputStream.socketRead0(Native Method)
[04:29:20] [Server thread/WARN]: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[04:29:20] [Server thread/WARN]: 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
[04:29:20] [Server thread/WARN]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
[04:29:20] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:567)
[04:29:20] [Server thread/WARN]: 	... 36 more
```

**Comment by Realizedd** [comment]
The error is saying that TokenManager is unable to make a connection at all, so I don’t think being able to set your own pool limit will help. But I’ll look into it.
