### ISSUE TITLE
tokenmanager multiple server one db

### ISSUE THREAD

**Issue by WolverStones** [Realizedd/TokenManager#31]
i have a tokenmanager connected to one db on one server it works on it 2 throws this error ...

`[TokenManager] There was an error while loading DataManager! If you believe this is an issue from the plugin, please contact the developer.
[04:28:16] [Server thread/INFO]: [TokenManager] Cause of error: Server is in ONLINE mode, but found table 'tokenmanager' does not have column 'uuid'! Please choose a different table name.
[04:28:16] [Server thread/WARN]: java.lang.Exception: Server is in ONLINE mode, but found table 'tokenmanager' does not have column 'uuid'! Please choose a different table name.
[04:28:16] [Server thread/WARN]: at me.realized.tokenmanager.data.database.MySQLDatabase.setup(MySQLDatabase.java:142)
[04:28:16] [Server thread/WARN]: at me.realized.tokenmanager.data.DataManager.handleLoad(DataManager.java:86)
[04:28:16] [Server thread/WARN]: at me.realized.tokenmanager.TokenManagerPlugin.load(TokenManagerPlugin.java:155)
[04:28:16] [Server thread/WARN]: at me.realized.tokenmanager.TokenManagerPlugin.onEnable(TokenManagerPlugin.java:106)
[04:28:16] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[04:28:16] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[04:28:16] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[04:28:16] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[04:28:16] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[04:28:16] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[04:28:16] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[04:28:16] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[04:28:16] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[04:28:16] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[04:28:16] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[04:28:16] [Server thread/INFO]: [TokenManager] Disabling TokenManager v3.2.2`

**Comment by Realizedd** [comment]
Make sure that both servers are in the same mode (online or offline).
