### ISSUE TITLE
Papi issue

### ISSUE THREAD

**Issue by successed** [Realizedd/TokenManager#36]
[19:18:57 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.3 generated an exception while executing task 380
java.lang.NoClassDefFoundError: me/realized/tm/api/TMAPI
        at com.extendedclip.papi.expansion.tokenmanager.TokenManagerExpansion$1.run(TokenManagerExpansion.java:91) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-146]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-146]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Realizedd** [comment]
The expansion is outdated, use %tm_tokens% instead.
