### ISSUE TITLE
TokenManager sending too many player lookup requests.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#5]
@RealizedMC With TokenManager v3.0.2, I keep experiencing this exact same error every time I restart my server. Is there any reason why TokenManager v3 needs to constantly look-up players?

```
[23:28:15] [pool-55-thread-1/WARN]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/0d6e7f2bb16e4e2e9f474cbe8125cf07
[23:28:15] [pool-55-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[23:28:15] [pool-55-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[23:28:15] [pool-55-thread-1/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[23:28:15] [pool-55-thread-1/WARN]: 	at me.realized.tokenmanager.util.profile.NameFetcher.getName(NameFetcher.java:48)
[23:28:15] [pool-55-thread-1/WARN]: 	at me.realized.tokenmanager.util.profile.ProfileUtil.getName(ProfileUtil.java:67)
[23:28:15] [pool-55-thread-1/WARN]: 	at me.realized.tokenmanager.util.profile.NameFetcher$NameCollectorTask.run(NameFetcher.java:88)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:28:15] [pool-55-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Realizedd** [comment]
It has to get the names of the /token top data. So 10 requests every time you restart.

**Comment by mibby** [comment]
How come TokenManager v2 didn't request skin updates to fetch the names? Would it be possible to add an option to not request current names at start-up and instead only when someone actually checks the top data for the first time since restart?

**Comment by Realizedd** [comment]
In 3407c06, I've made it so if mojang API fails, it will use another API to get the names. Also, it won't spam errors in console anymore as well
